### ISSUE TITLE
User / password and port configuration

### ISSUE THREAD

**Issue by UncleSamSwiss** [mozz100/node-logitechmediaserver#1]
For my use of your great NPM package in [ioBroker.squeezebox](https://github.com/UncleSamSwiss/ioBroker.squeezebox), I would like to have the user name, password and port of the Logitech Media Server configurable.

If you would like, I can create a pull request with the changes, but in any case I would need your help for publishing the new version to NPM so I can use it. Please let me know what works best for you.

Thanks for your effort in advance!

**Comment by mozz100** [comment]
Ah, I'm pleased that this code I wrote so long ago is proving useful.  Thank you for getting in touch. I'm afraid I have no time to work on it myself.  If you were able to do a pull request, I'd be very pleased to incorporate new code and publish a newer version to npm.  Just send a pull request and I'll see if I can remember how to do it with npm!

**Comment by UncleSamSwiss** [comment]
Thank you for your response. I created the pull request #2. If you're ok with it, please merge it back, do an "npm publish" in its root directory and then you can close this issue.

**Comment by mozz100** [comment]
Thanks - in process of doing npm publish.  Hey - are you unclesamswiss on npm? I'd happily make you a contributor on there so you can do things from now on.
I no longer use (or possess) any of the Logitech kit, so I'm unable to develop or test any of this code!

**Comment by mozz100** [comment]
Published new version to npm at https://www.npmjs.com/package/logitechmediaserver

**Comment by UncleSamSwiss** [comment]
Thanks so much for the publishing and for inviting me to work on the project!
I just updated my adapter, users will be thankful for the new features.
Yes, I'm [unclesamswiss](https://www.npmjs.com/~unclesamswiss) on NPM.

**Comment by mozz100** [comment]
Ah, that's really nice to hear.  It's a pleasure to share the code and to know that it's proving useful. Thank you.  I've made you a collaborator on npm as well.
